version: '3'

services:
  database:
    build:
      context: ./mongoDocker/
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongodb-data:/data/db

  fer_model:
    build:
      context: ./models/
    container_name: fer_model
    ports:
      - "8080:8080"
    networks:
      - mongo-network

  streamlit-app:
    build:
      context: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - database
      - fer_model
    networks:
      - mongo-network
    environment:
      - API_KEY=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

volumes:
  mongodb-data:

networks:
  mongo-network: