version: '3'

services:
  mongodb:
    build:
      context: ./mongoDocker/
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  streamlit-app:
    build:
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

volumes:
  mongodb-data:
