version: '3'

services:
  database:
    build:
      context: ./mongoDocker/
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongodb-data:/data/db

  streamlit-app:
    build:
      context: .
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - database
    networks:
      - mongo-network
    environment:
      - API_KEY=UJGOceHjyxw1ONsrcllJzmXDffiF8XRK

volumes:
  mongodb-data:

networks:
  mongo-network: